development:
  adapter: postgresql
  encoding: unicode
  database: ejc_development
  pool: 5
  host: localhost
  username: ejc
  password: ejc

production:
  adapter: postgresql
  encoding: unicode
  database: ejc_production
  pool: 5
  host: localhost
  username: ejc
  password: ejc
